version: '3.8'

services:
  backend-service:
    build: .
    image: rag3-image
    container_name: rag3-backend-container
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8080:80"
    volumes:
      - .:/app
    networks:
      - app-network

  ollama-service:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ollama:/root/.ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    driver: local
