# services:
#   app:
#     build: .
#     container_name: rag3-backend
#     command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
#     ports:
#       - 8080:80
#     volumes:
#       - .:/app

version: '3.8'

services:
  app:
    build: .
    container_name: rag3-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8080:80"
    volumes:
      - .:/app
    networks:
      - app-network

  second-service:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ollama:/root/.ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    driver: local
